version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: green-fashion-postgres
    environment:
      POSTGRES_DB: green_fashion_score
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:


